Update Sdk version
ferredoxin/QNotified pull request #1118
Opened 2021-11-03 05:17 UTC by NextAlone

Signed-off-by: NextAlone <12210746+NextAlone@users.noreply.github.com>

# PR

## 介绍

## 检查列表

- [ ] Tested

2021-11-03 05:18 UTC, singleNeuron approved these changes

2021-11-03 05:34 UTC, singleNeuron requested changes
等我去试一下azure正常不正常

2021-11-03 05:37 UTC, NextAlone commented
> 等我去试一下azure正常不正常

好耶

2021-11-03 06:09 UTC, singleNeuron approved these changes

2021-11-03 13:51 UTC, qwq233 commented
没必要吧 老版本build tool不能构筑？

2021-11-03 13:52 UTC, qwq233 commented
没必要吧 老版本build tool不能构筑？

2021-11-03 13:52 UTC, NextAlone commented
@qwq233 等华亭鹤更AGP, 没必要动build-tools了

2021-11-03 13:53 UTC, NextAlone commented
@qwq233 你的jenkis没有31的platform？

2021-11-04 03:21 UTC, qwq233 commented
> @qwq233 你的jenkis没有31的platform？

没 回家处理

2021-11-06 20:41 UTC, closed without merging