repeatTextMessage with atInfo
ferredoxin/QNotified pull request #1140
Opened 2021-11-14 17:59 UTC by keta1

# PR

## 介绍x

## 检查列表

- [x] Tested

2021-11-14 21:05 UTC, NextAlone requested changes

2021-11-14 21:05 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/bridge/ChatActivityFacade.java
> +                if (argt[2].equals(_SessionInfo()) || argt[2].equals(load("com/tencent/mobileqq/activity/aio/BaseSessionInfo"))) {
```suggestion
                if (argt[2].equals(_SessionInfo()) || argt[2].equals(_BaseSessionInfo())) {
```

2021-11-15 00:24 UTC, NextAlone approved these changes

2021-11-15 04:10 UTC, qwq233 approved these changes

2021-11-15 04:14 UTC, merged