fix: #1160
ferredoxin/QNotified pull request #1161
Opened 2021-11-22 15:53 UTC by singleNeuron

Signed-off-by: singleNeuron <Cryolitia@gmail.com>

# PR

## 介绍

## 检查列表

- [ ] Tested

2021-11-22 15:55 UTC, keta1 requested changes
我这样运行坏了

2021-11-22 15:56 UTC, cinit submitted a review, later dismissed

2021-11-22 17:22 UTC, keta1 commented
> > 我这样运行坏了
> 
> 怎么坏的

你是没编译运行吗

2021-11-22 17:22 UTC, singleNeuron commented
@keta1 我怎么可能编译运行

2021-11-23 11:56 UTC, keta1 approved these changes

2021-11-23 14:59 UTC, merged