Update azure-pipelines.yml
ferredoxin/QNotified pull request #1171
Opened 2021-11-26 16:26 UTC by singleNeuron

Signed-off-by: singleNeuron <Cryolitia@gmail.com>

# PR

## 介绍

## 检查列表

- [x] Tested

2021-11-26 17:19 UTC, NextAlone approved these changes

2021-11-27 00:43 UTC, qwq233 requested changes

2021-11-27 00:43 UTC, qwq233 commented on azure-pipelines.yml
> +      git push -f origin HEAD:master
有些commit这边没有的亲亲

2021-11-27 01:34 UTC, singleNeuron commented on azure-pipelines.yml
> +      git push -f origin HEAD:master
所以push -f了

2021-11-27 01:35 UTC, qwq233 commented
?

2021-11-27 01:36 UTC, singleNeuron commented
> ?

cr里面回复你了，你看一下

2021-11-27 01:39 UTC, qwq233 commented
我看个毛 在学校 晚上再说

2021-11-27 01:39 UTC, singleNeuron commented
> 我看个毛 在学校 晚上再说

好，你快回来，这周也有大惊喜

2021-11-27 01:44 UTC, cinit approved these changes

2021-11-27 01:44 UTC, merged