feat: replace ExFriendManager with ConfigManager in some feature
ferredoxin/QNotified pull request #1186
Opened 2021-12-12 02:32 UTC by qwq233

details see commit msg
tested on my device

2021-12-12 02:35 UTC, singleNeuron requested changes
不要折腾什么requireNonNull，太不优雅了，有需要就直接kotlin重写

2021-12-14 11:46 UTC, keta1 requested changes
这样就不会分账号设置了

2021-12-14 11:49 UTC, keta1 commented
ExFriendManager 弃用始于发现使用会出现丢失配置/qq卡死等各种bug
但后续发现 ConfigManager 其实也会
只是因为 ExFriendManager 数据量比较大，最容易出现
在某次鸽子的提交中 ConfigManager 实质上已经使用mmkv
ExFriendManager 是特殊的 ConfigManager 
也已经使用mmkv
所以现在是无意义的

2021-12-14 11:49 UTC, closed without merging

2021-12-17 01:44 UTC, qwq233 commented
> ExFriendManager 弃用始于发现使用会出现丢失配置/qq卡死等各种bug 但后续发现 ConfigManager 其实也会 只是因为 ExFriendManager 数据量比较大，最容易出现 在某次鸽子的提交中 ConfigManager 实质上已经使用mmkv ExFriendManager 是特殊的 ConfigManager 也已经使用mmkv 所以现在是无意义的

主要是会报弃用的warn



> 这样就不会分账号设置了

forCurrentAccount应该会获取当前账号的吧至少按我的理解的话

2021-12-17 01:48 UTC, keta1 commented
@qwq233 把注解删了，摆烂就好

2021-12-17 01:49 UTC, NextAlone commented
@keta1 摆烂