Update copyright
ferredoxin/QNotified pull request #1209
Opened 2021-12-29 12:15 UTC by NextAlone

# PR

## 介绍

## 检查列表

- [ ] Tested

2021-12-29 12:18 UTC, NextAlone commented
已skip ci

2021-12-29 12:32 UTC, qwq233 requested changes

2021-12-29 12:32 UTC, qwq233 commented on libs/mmkv/Android/src/main/java/com/tencent/mmkv/MMKV.java
> + * QNotified - An Xposed module for QQ/TIM
这里别赛

2021-12-29 12:32 UTC, qwq233 commented on libs/stub/src/main/java/com/tencent/mobileqq/app/IphoneTitleBarActivity.java
> + * Copyright (C) 2019-2022 dmca@ioctl.cc
同上

2021-12-29 12:37 UTC, NextAlone commented on libs/mmkv/Android/src/main/java/com/tencent/mmkv/MMKV.java
> + * QNotified - An Xposed module for QQ/TIM
好了

2021-12-29 14:08 UTC, qwq233 requested changes

2021-12-29 14:08 UTC, qwq233 commented on app/src/main/java/me/zpp0196/qqpurify/fragment/AboutPreferenceFragment.java
> +/*
qq净化也别赛最好 刚看到

2021-12-29 14:17 UTC, NextAlone commented on app/src/main/java/me/zpp0196/qqpurify/fragment/AboutPreferenceFragment.java
> +/*
坏，

2021-12-29 23:56 UTC, qwq233 approved these changes

2021-12-30 05:46 UTC, keta1 approved these changes

2021-12-30 05:46 UTC, merged