Qwq233 patch 3
ferredoxin/QNotified pull request #1236
Opened 2022-01-22 07:21 UTC by qwq233

- [x] Tested

2022-01-22 07:23 UTC, Cryolitia requested changes

2022-01-22 07:23 UTC, Cryolitia commented on app/src/main/java/me/singleneuron/qn_kernel/tlb/UiTable.kt
> +            uiCategory {
太丑陋了 从这里加if就行，这是DSL，里面也是函数体的

2022-01-22 07:24 UTC, qwq233 commented on app/src/main/java/me/singleneuron/qn_kernel/tlb/UiTable.kt
> +            uiCategory {
哦

2022-01-22 12:19 UTC, NextAlone approved these changes

2022-01-24 06:05 UTC, qwq233 commented
这pr神经元不鸟我就合了啊

2022-01-24 06:05 UTC, qwq233 commented
挂着半天没动静

2022-01-24 06:10 UTC, Cryolitia approved these changes

2022-01-24 06:10 UTC, merged