[skip ci]Delete related Telegram group information
ferredoxin/QNotified pull request #358
Opened 2020-10-17 16:04 UTC by qwq233

## 介绍 / Description
Given that the related group has been dissolved, has deleted related Telegram group information

## 更改内容 / Types of Changes

- [ ] 内核 Core
- [ ] 修复 Bugfix
- [ ] 新功能 New feature
- [ ] 增强/优化 Enhancement/optimization
- [x] 文档 Documentation
- [ ] UI界面 User interface

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

* 

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [ ] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2020-10-17 16:13 UTC, JasonKhew96 approved these changes

2020-10-17 18:00 UTC, singleNeuron requested changes
把telegram改成机器人吧

2020-10-17 23:11 UTC, singleNeuron requested changes

2020-10-17 23:11 UTC, singleNeuron commented on app/src/main/java/nil/nadph/qnotified/activity/DonateActivity.java
>          ll.addView(newListItemButton(this, "更新频道", null, "@QNotified", clickToUrl("https://t.me/QNotified")));
```suggestion
        ll.addView(newListItemButton(this, "更新频道", null, "@QNotified", clickToUrl("https://t.me/QNotified_bot")));
```

2020-10-17 23:22 UTC, singleNeuron requested changes

2020-10-17 23:22 UTC, singleNeuron commented on app/src/main/java/nil/nadph/qnotified/activity/DonateActivity.java
> +        ll.addView(newListItemButton(this, "更新频道", null, "@QNotified", clickToUrl("https://t.me/QNotified_bot")));
```suggestion
        ll.addView(newListItemButton(this, "更新频道", null, "@QNotified", clickToUrl("https://t.me/QNotified")));
```

2020-10-17 23:22 UTC, singleNeuron commented on app/src/main/java/nil/nadph/qnotified/activity/DonateActivity.java
>          ll.addView(newListItemButton(this, "Telegram", "点击私信", "Auride", clickToUrl("https://t.me/Auride")));
```suggestion
        ll.addView(newListItemButton(this, "Telegram", "点击私信", "客服机器人", clickToUrl("https://t.me/QNotified_bot")));
```

2020-10-17 23:31 UTC, singleNeuron approved these changes

2020-10-18 03:37 UTC, huajijam commented
Merge Commit PLZ

2020-10-18 03:58 UTC, singleNeuron commented
> Merge Commit PLZ

u can u up

2020-10-18 04:03 UTC, qwq233 commented
> Merge Commit PLZ

working on this
The master branch of my fork repository is a bit messy and has been extensively modified by me. May be troublesome

2020-10-18 04:13 UTC, qwq233 commented
> > Merge Commit PLZ
> 
> working on this
> The master branch of my fork repository is a bit messy and has been extensively modified by me. May be troublesome

done

2020-10-18 04:17 UTC, huajijam commented
好耶

2020-10-18 04:18 UTC, merged