Fix FileRecvRedirect on Android 11
ferredoxin/QNotified pull request #371
Opened 2020-11-14 00:44 UTC by nakixii

## 介绍 / Description

在Android 11上，/storage/emulated/0/Android/data目录不允许被访问，所以我们需要另辟蹊径。

## 更改内容 / Types of Changes

- [Android 11 存储重定向修复] 修复 Bugfix

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [ ] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2020-11-14 03:49 UTC, singleNeuron requested changes

2020-11-14 03:49 UTC, singleNeuron commented on app/src/main/java/nil/nadph/qnotified/hook/FileRecvRedirect.java
>              if (getHostVersionCode32() > 1334) {
请把这里的1334换成https://github.com/ferredoxin/QNotified/blob/master/app/src/main/java/me/singleneuron/util/QQVersion.java
中定义的常量

2020-11-14 07:19 UTC, nakixii commented on app/src/main/java/nil/nadph/qnotified/hook/FileRecvRedirect.java
>              if (getHostVersionCode32() > 1334) {
换了

2020-11-14 10:54 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/hook/FileRecvRedirect.java
>              if (getHostVersionCode32() > 1334) {
`/storage/self/primary/` 有没有可能在安卓5.0不存在(或者无法被访问)？

2020-11-14 12:30 UTC, nakixii commented on app/src/main/java/nil/nadph/qnotified/hook/FileRecvRedirect.java
>              if (getHostVersionCode32() > 1334) {
/storage/self是安卓6.0开始加入的，/mnt/sdcard安卓5.0有

2020-11-14 16:02 UTC, qwq233 commented
建议将这些commit合并为一个commit

2020-11-14 16:05 UTC, singleNeuron commented
> 建议将这些commit合并为一个commit

建议不要理会这个强迫症的建议

2020-11-14 16:23 UTC, qwq233 commented
> > 建议将这些commit合并为一个commit
> 
> 建议不要理会这个强迫症的建议

= =就改几行代码用6个commit 有个commit build failed 有个commit甚至是空内容
再说废commit越积越多代码管理会很麻烦（虽然貌似这个项目也不大不怎么需要

2020-11-14 16:51 UTC, username-long111 commented
浪费时间

________________
2855669787@qq.com




---Original---
From: &quot;gao_cai_sheng&quot;<notifications@github.com&gt;
Date: Sun, Nov 15, 2020 00:23 AM
To: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
Cc: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
Subject: Re: [ferredoxin/QNotified] Fix FileRecvRedirect on Android 11 (#371)




   
建议将这些commit合并为一个commit
  
建议不要理会这个强迫症的建议
  
= =就改几行代码用6个commit 有个commit build failed 有个commit甚至是空内容
 再说废commit越积越多代码管理会很麻烦（虽然貌似这个项目也不大不怎么需要
 
&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-17 09:59 UTC, huajijam requested changes
这将导致旧版本TIM无法正常触发存储重定向

2020-11-22 12:16 UTC, closed without merging