适配8.4.17
ferredoxin/QNotified pull request #377
Opened 2020-11-19 04:53 UTC by Elaboration12138

## 介绍 / Description

## 更改内容 / Types of Changes

- [x] 修复 Bugfix

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

* 适配8.4.17，修复新版圆头像，昵称马赛克（仅8.4.17），群聊一起嗨（仅8.4.17）

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [ ] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2020-11-19 06:06 UTC, 122cygf commented
但是这么改的话其他版本不适配了啊，建议写上版本判断

2020-11-19 06:16 UTC, Elaboration12138 commented
> 我简单看了一下，这么改的话旧版本还适配吗？

上个版本也没适配😂，那我看看加一下

2020-11-19 06:17 UTC, Elaboration12138 commented
> 我简单看了一下，这么改的话旧版本还适配吗？

好像不行，8.4.10也没修。那我看看加一下吧

2020-11-19 06:20 UTC, cinit requested changes
直接单改类名必然会导致旧版本无法兼容, 请将相关类的loadClass访问通过`Initiator.java`，如`Initiator._BaseChatBie()`来获取QQ的`BaseChatPie.class`

2020-11-19 06:36 UTC, Elaboration12138 commented
> 直接单改类名必然会导致旧版本无法兼容, 请将相关类的loadClass访问通过`Initiator.java`，如`Initiator._BaseChatBie()`来获取QQ的`BaseChatPie.class`

明白了，方法名如何实现同样效果，部分方法名如马赛克取消了混淆，"t"->"enableMosaicEffect"

2020-11-19 12:41 UTC, JasonKhew96 commented
8.4.18 都出来了...
直接适配这个版本吧（~~如果没意外的话，应该跟8.4.17一样~~）

2020-11-19 16:21 UTC, 122cygf commented
@JasonKhew96 可太惨了，有人刚适配一点8417

2020-11-19 16:37 UTC, Lagrio commented
@122cygf 这种隔天更新的小版本号应该是不会改混淆的

2020-11-20 02:31 UTC, Neubulae commented
TIM 有适配吗(

2020-11-20 02:34 UTC, Elaboration12138 commented
> TIM 有适配吗(

没有

2020-11-20 02:37 UTC, Neubulae commented
> > TIM 有适配吗(
> 
> 没有

oompf

2020-11-22 04:00 UTC, cinit requested changes

2020-11-22 04:00 UTC, cinit commented on app/src/main/java/me/kyuubiran/hook/RemovePlayTogether.java
> +                XposedHelpers.findAndHookMethod(load("agpr"), "d", new XC_MethodHook(43) {
建议 `Utils.getHostVersionCode() >= QQVersion....` 多点版本支持(代码乱不乱不重要, 关键是用多版本能用)

2020-11-22 04:03 UTC, Elaboration12138 commented on app/src/main/java/me/kyuubiran/hook/RemovePlayTogether.java
> +                XposedHelpers.findAndHookMethod(load("agpr"), "d", new XC_MethodHook(43) {
恩恩。Java和kotlin不太行，学习一下改一下

2020-11-22 06:27 UTC, Elaboration12138 reviewed
其他的应该没问题了

2020-11-22 06:41 UTC, Lagrio commented
建议把8410一起适配了

2020-11-22 07:11 UTC, Elaboration12138 commented
DexKit.C_TogetherControlHelper这个如何一个旧的一个新的

2020-11-22 07:28 UTC, Lagrio approved these changes

2020-11-22 08:50 UTC, cinit approved these changes

2020-11-22 08:53 UTC, merged