[skip ci]Modified to comply with markdownlint rules
ferredoxin/QNotified pull request #379
Opened 2020-11-21 10:40 UTC by qwq233

# Modified to comply with markdownlint rules  

## 介绍 / Description
Modified to comply with markdownlint rules

## 更改内容 / Types of Changes

- [x] 文档 Documentation

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2020-11-22 02:57 UTC, cinit approved these changes

2020-11-22 04:21 UTC, huajijam requested changes
请去掉无意义的空变动

2020-11-22 04:26 UTC, qwq233 commented
> 请去掉无意义的空变动

![image](https://user-images.githubusercontent.com/20317838/99894164-bf9b5000-2cbd-11eb-899d-e07143ec1fc9.png)
此处空行是为了修复这个
![image](https://user-images.githubusercontent.com/20317838/99894202-dcd01e80-2cbd-11eb-963c-22d7fb8c7fb0.png)
此处删除空格是为了这个

2020-11-22 06:31 UTC, Lagrio approved these changes

2020-11-27 12:39 UTC, singleNeuron approved these changes

2020-12-05 11:26 UTC, huajijam approved these changes

2020-12-05 11:26 UTC, merged