[skip ci] Init support 8.5.0
ferredoxin/QNotified pull request #397
Opened 2020-12-26 19:49 UTC by Elaboration12138

# 适配8.5.0

## 介绍 / Description

初步适配8.5.0

## 更改内容 / Types of Changes

- [x] 修复 Bugfix

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2020-12-27 14:03 UTC, Lagrio approved these changes

2020-12-28 05:09 UTC, cinit requested changes
`getBusinessHandler()` 存在问题

2020-12-28 07:25 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/util/Utils.java
> +                    return invoke_virtual(appInterface, "getBusinessHandler", type, String.class,
改成...return getBusinessHandler("com/tencent/mobileqq/app/FriendListHandler");

public static Object getBusinessHandler(String type) {
...
return invoke_virtual(appInterface, "getBusinessHandler", type, String.class, cl_bh);
...
}

返回了空指针

2020-12-28 07:52 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/util/Utils.java
> +                    return invoke_virtual(appInterface, "getBusinessHandler", type, String.class,
我们可以删除方法 `Utils.getBusinessHandler(任何参数?)` , 因为唯一会用到这个方法的地方是 `Utils.getFriendListHandler()` , 我们只要把 `Utils.getBusinessHandler(?)` 丢到 `Utils.getFriendListHandler()` 里重新实现一下, 然后就可以删除 `Utils.getBusinessHandler(?)` 了

2020-12-28 09:21 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/util/Utils.java
> +                    return invoke_virtual(appInterface, "getBusinessHandler", type, String.class,
已弃用getBusinessHandler()，且无Exception了

2020-12-28 13:08 UTC, cinit approved these changes

2020-12-28 14:43 UTC, JasonKhew96 approved these changes

2020-12-28 14:45 UTC, merged