Update SimplifyQQSettingMe.kt & Hide BaseApk in QQPurify
ferredoxin/QNotified pull request #404
Opened 2020-12-30 16:27 UTC by NextAlone

# Update SimplifyQQSettingMe.kt & Hide BaseApk in QQPurify

## 介绍 / Description

## 更改内容 / Types of Changes

- [x] 修复 Bugfix

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2020-12-30 18:22 UTC, Lagrio approved these changes

2020-12-31 04:09 UTC, cinit requested changes

2020-12-31 04:09 UTC, cinit commented on app/src/main/java/me/singleneuron/hook/HideProfileBubble.kt
> +            QQVersion.QQ_8_4_5 -> "V"
839 S, 841 V

2020-12-31 13:45 UTC, cinit approved these changes

2020-12-31 13:46 UTC, merged