[skip ci] Change UI
ferredoxin/QNotified pull request #406
Opened 2020-12-31 18:36 UTC by Lagrio

# Title  

## 介绍 / Description

更改界面与文本
## 更改内容 / Types of Changes

- [ ] 内核 Core
- [ ] 修复 Bugfix
- [ ] 新功能 New feature
- [ ] 增强/优化 Enhancement/optimization
- [ ] 文档 Documentation
- [x] UI界面 User interface

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2020-12-31 19:31 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/activity/ConfigV2Activity.java
> +                        .setMessage("如模块无法使用，EdXp可尝试取消优化+开启兼容模式  ROOT用户可尝试 用幸运破解器-工具箱-移除odex更改 移除QQ与本模块的优化, 太极尝试取消优化")
```suggestion
                        .setMessage("如模块无法使用，EdXp可尝试取消优化+开启兼容模式  ROOT用户可尝试用 幸运破解器-工具箱-移除odex更改 移除QQ与本模块的优化, 太极尝试取消优化")
```

2020-12-31 19:33 UTC, NextAlone approved these changes

2020-12-31 19:59 UTC, singleNeuron commented
你commit到我的分支啊，把我的分支关了自己开一个干啥

2021-01-01 03:02 UTC, singleNeuron requested changes

2021-01-01 03:02 UTC, singleNeuron commented on app/src/main/res/values-v23/styles.xml
> +<?xml version="1.0" encoding="utf-8"?>
https://github.com/ferredoxin/QNotified/pull/405/commits/24cb0a543771c014093596a8300811dec1fd4740

这样修，别单独建个v23

2021-01-01 04:31 UTC, Lagrio commented on app/src/main/res/values-v23/styles.xml
> +<?xml version="1.0" encoding="utf-8"?>
哦

2021-01-01 06:29 UTC, singleNeuron approved these changes

2021-01-01 06:54 UTC, cinit approved these changes

2021-01-01 06:54 UTC, merged