多选撤回消息
ferredoxin/QNotified pull request #432
Opened 2021-01-14 18:51 UTC by ketal178

# 多选撤回消息  

## 介绍 / Description
多选消息后，增加撤回按钮。

## 更改内容 / Types of Changes

- [ ] 内核 Core
- [ ] 修复 Bugfix
- [x] 新功能 New feature
- [ ] 增强/优化 Enhancement/optimization
- [ ] 文档 Documentation
- [ ] UI界面 User interface

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [ ] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-01-15 07:57 UTC, qwq233 requested changes
ndk版本对不上

2021-01-15 09:09 UTC, JasonKhew96 commented
> ndk版本对不上

ci的问题，另外开一个pr修吧
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

ndk该更新了

2021-01-15 10:41 UTC, qwq233 approved these changes

2021-01-15 11:01 UTC, qwq233 commented
能不能尽量减少下无用的commit = =
整理了下，现在应该好很多了

2021-01-15 11:03 UTC, ketal178 commented
> 能不能尽量减少下无用的commit = =
> 整理了下，现在应该好很多了

我不太会用git,你能替我完成一下吗

2021-01-15 11:06 UTC, NextAlone approved these changes

2021-01-15 11:23 UTC, JasonKhew96 approved these changes

2021-01-15 11:28 UTC, merged

2021-01-16 05:07 UTC, singleNeuron commented
> 能不能尽量减少下无用的commit = =
> 整理了下，现在应该好很多了

rebase merge啊

2021-01-16 15:42 UTC, ketal178 commented
> > 能不能尽量减少下无用的commit = =
> > 整理了下，现在应该好很多了
> 
> rebase merge啊

我能说我只会commit pull push吗（狗头保命）

2021-01-16 15:44 UTC, NextAlone commented
@ketal178 你可以直接在as里，reset current branch to here 然后 再 commit 然后 force commit

2021-01-16 15:45 UTC, singleNeuron commented
@NextAlone 然后他直接给你force push进主分支了（

2021-01-16 15:45 UTC, qwq233 commented
@ketal178 或者你用vsc的话在源代码栏三个点里边能找到一些常用的玩意

2021-01-16 15:45 UTC, qwq233 commented
@ketal178 实在不行无脑git+狂按tab解决

2021-01-16 15:46 UTC, ketal178 commented
> @NextAlone 然后他直接给你force push进主分支了（

没权限能push进去？