Fixed can't revoke message on TIM
ferredoxin/QNotified pull request #442
Opened 2021-01-16 13:38 UTC by ketal178

Fixed can't hook multi action on TIM

# Title  Update QQMessageFacade.java and MultiActionHook.java

## 介绍 / Description
Fixed can't revoke message on TIM
Fixed can't hook multi action on TIM

## 更改内容 / Types of Changes

- [ ] 内核 Core
- [x] 修复 Bugfix
- [ ] 新功能 New feature
- [ ] 增强/优化 Enhancement/optimization
- [ ] 文档 Documentation
- [ ] UI界面 User interface

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  None

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-01-16 13:42 UTC, singleNeuron submitted a review, later dismissed

2021-01-16 13:42 UTC, singleNeuron commented on app/src/main/java/nil/nadph/qnotified/bridge/QQMessageFacade.java
> +                long version = getHostVersionCode();
you may need to create a class like https://github.com/ferredoxin/QNotified/blob/master/app/src/main/java/me/singleneuron/util/QQVersion.java for tim. Do not use meaningless number anytime!
and put methods and so on in https://github.com/ferredoxin/QNotified/blob/master/app/src/main/java/me/singleneuron/qn_kernel/tlb/ConfigTable.kt

2021-01-16 13:42 UTC, singleNeuron commented on app/src/main/java/nil/nadph/qnotified/hook/MultiActionHook.java
> +            if (version >= 1090) { //3.3.0-3.3.1(latest)
the same

2021-01-16 15:31 UTC, ketal178 commented on app/src/main/java/nil/nadph/qnotified/hook/MultiActionHook.java
> +            if (version >= 1090) { //3.3.0-3.3.1(latest)
怎么合并Commit

2021-01-16 15:50 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/MultiActionHook.java
> +            if (version >= 1090) { //3.3.0-3.3.1(latest)
git reset+git push -f

2021-01-16 15:57 UTC, ketal178 commented on app/src/main/java/nil/nadph/qnotified/hook/MultiActionHook.java
> +            if (version >= 1090) { //3.3.0-3.3.1(latest)
> git reset+git push -f

git reset --hard HEAD^^
git push -f
这样吗

2021-01-16 16:10 UTC, ketal178 commented on app/src/main/java/nil/nadph/qnotified/hook/MultiActionHook.java
> +            if (version >= 1090) { //3.3.0-3.3.1(latest)
> git reset+git push -f

vans了，用代码交流就是方便

2021-01-17 10:45 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
> +        } else if(getHostVersionCode32() >= TIMVersion.TIM_3_1_1) {
does using qq or tim version code at the same time cause problems?

2021-01-17 10:46 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
> +        } else if(getHostVersionCode32() >= TIMVersion.TIM_3_1_1) {
when at lower qq version

2021-01-18 06:01 UTC, NextAlone approved these changes

2021-01-18 07:54 UTC, qwq233 commented
请把timconfigtable的内容整合到https://github.com/ferredoxin/QNotified/blob/master/app/src/main/java/me/singleneuron/qn_kernel/tlb/ConfigTable.kt

2021-01-18 07:55 UTC, qwq233 requested changes
请把timconfigtable的内容整合到https://github.com/ferredoxin/QNotified/blob/master/app/src/main/java/me/singleneuron/qn_kernel/tlb/ConfigTable.kt

2021-01-18 08:03 UTC, ketal178 commented
> 请把timconfigtable的内容整合到https://github.com/ferredoxin/QNotified/blob/master/app/src/main/java/me/singleneuron/qn_kernel/tlb/ConfigTable.kt

整合到一起，TIM与QQ的版本号冲突是个问题，我试试

2021-01-18 08:04 UTC, qwq233 commented
@ketal178 没事你尽量 实在处理不了的话我看看有没有后续问题就approve

2021-01-18 08:13 UTC, ketal178 commented
> @ketal178 没事你尽量 实在处理不了的话我看看有没有后续问题就approve



> @ketal178 没事你尽量 实在处理不了的话我看看有没有后续问题就approve

主要是在getConfig只传一个Class的SimpleName，在里面判断是否为TIM就缺Context，无脑getApplication怕出什么效率问题

2021-01-18 08:57 UTC, ketal178 commented
> > @ketal178 没事你尽量 实在处理不了的话我看看有没有后续问题就approve
主要是在ConfigTable#getConfig只传一个Class的SimpleName，在里面判断是否为TIM就缺Context，无脑getApplication怕出什么效率问题

2021-01-18 09:25 UTC, cinit commented
@ketal178 能不能把ConfigTable接口化，然后在QQ(插件)启动的时候根据宿主Context是QQ还是TIM(例如用QqConfigTableProvider或者TimConfigTableProvider)去实例化

2021-01-18 09:26 UTC, ketal178 commented
> @ketal178 能不能把ConfigTable接口化，然后在QQ(插件)启动的时候根据宿主Context是QQ还是TIM(例如用QqConfigTableProvider或者TimConfigTableProvider)去实例化

说的好，show your code

2021-01-18 09:27 UTC, cinit commented
@ketal178 神经元的代码我不敢乱动啊

2021-01-18 09:28 UTC, ketal178 commented
> @ketal178 神经元的代码我不敢乱动啊

你觉得我敢吗，我尽量都没动别人代码

2021-01-19 17:25 UTC, qwq233 approved these changes

2021-01-19 17:54 UTC, NextAlone approved these changes

2021-01-20 05:39 UTC, lliioollcn approved these changes

2021-01-22 04:04 UTC, cinit requested changes

2021-01-22 04:04 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/bridge/QQMessageFacade.java
> +            Object msg2 = invoke_static_any(DexKit.doFindClass(DexKit.C_MSG_REC_FAC), msg, Initiator._MessageRecord(), Initiator._MessageRecord());
在TIM2.3.0, QQ8.0.0和QQ8.5.5这三个版本都测试过了吗?

2021-01-22 04:04 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/StartupHook.java
> +                        ConfigTable.INSTANCE.setTim(isTim(ctx));
此处可能导致模块在某些改包框架上完全无法使用(kotlin依赖库与宿主冲突), 请将 `ConfigTable.INSTANCE.setTim(isTim(ctx));` 移动到 ` MainHook.performHook()` 方法内

2021-01-22 04:55 UTC, cinit approved these changes

2021-01-22 05:01 UTC, merged

2021-01-22 09:44 UTC, singleNeuron commented
@ketal178 这个我在学校已经构思好了 今明两天就pr

2021-01-22 10:01 UTC, singleNeuron commented
@ketal178 @cinit 我严重怀疑你们是两头大蠢驴，判断个包名还要context，lpparam.packageName，请

2021-01-22 10:04 UTC, cinit commented
@singleNeuron 我就是为了不要让lpparam到处乱飞, 以及, Initiator初始化之前,  避免执行**任何**kotlin代码

2021-01-22 10:05 UTC, singleNeuron commented
@cinit md 我忘了kotlin这回事了，所以你能不能赶紧把这个Bug修好

2021-01-22 10:24 UTC, ketal178 commented
> @ketal178 @cinit 我严重怀疑你们是两头大蠢驴，判断个包名还要context，lpparam.packageName，请

技术实力不够，望海涵

2021-01-22 10:30 UTC, singleNeuron commented
@ketal178 我说话比较直别放心上，我稍微改了一下麻烦帮忙测试一下。
https://github.com/ferredoxin/QNotified/pull/454

2021-01-22 10:34 UTC, ketal178 commented
> @ketal178 我说话比较直别放心上，我稍微改了一下麻烦帮忙测试一下。
> #454

没事。
我测试下试试