Refactor some class-find-way with DexKit.java instead of ConfigTable.kt
ferredoxin/QNotified pull request #467
Opened 2021-01-24 17:14 UTC by NextAlone

Signed-off-by: NextAlone <12210746+NextAlone@users.noreply.github.com>

# Refactor some class-find-way with DexKit.java instead of ConfigTable.kt

## 介绍 / Description

## 更改内容 / Types of Changes

- [ ] 内核 Core
- [ ] 修复 Bugfix
- [ ] 新功能 New feature
- [x] 增强/优化 Enhancement/optimization
- [ ] 文档 Documentation
- [ ] UI界面 User interface

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [ ] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-01-25 12:55 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +    public static final int DEOBF_NUM_N = 7;
Change to 6 plz

2021-01-25 13:08 UTC, cinit requested changes

2021-01-25 13:08 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
确认是0x14?

2021-01-25 13:10 UTC, ketal178 commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
我怀疑他没用测试（

2021-01-25 13:17 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
@kyuubiran

2021-01-25 13:18 UTC, KyuubiRan commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
?我不知道 不要问我 我不会dexkit

2021-01-25 13:19 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
额。0x0e

2021-01-25 13:21 UTC, ketal178 commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
当初的0x49怎么过的（

2021-01-25 13:26 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
可是我在8.5.0(1596)没找到字符串`"IntimateDrawer"`啊

2021-01-25 13:29 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
?我不知道 不要问我 我当时不会dexkit

2021-01-25 13:30 UTC, ketal178 commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
> ?我不知道 不要问我 我当时不会dexkit

神秘（

2021-01-25 13:31 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
> ?我不知道 不要问我 我当时不会dexkit

How had you done it?

2021-01-25 16:10 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
> How had you done it?

imitation?

2021-01-25 16:11 UTC, NextAlone commented on app/src/main/java/nil/nadph/qnotified/util/DexKit.java
> +                return new byte[][]{new byte[]{0x14, 0x49, 0x6e, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x77, 0x65, 0x72}};
> 可是我在8.5.0(1596)没找到字符串`"IntimateDrawer"`啊

哦，当时不知道是字符串哦，谁知道呢。

2021-01-26 11:21 UTC, cinit submitted a review, later dismissed

2021-01-26 11:48 UTC, lliioollcn approved these changes

2021-01-26 12:01 UTC, cinit reviewed
@singleNeuron sth not working

2021-01-26 13:17 UTC, ketal178 approved these changes

2021-01-27 05:24 UTC, cinit approved these changes

2021-01-27 06:19 UTC, merged