feat(Mute): add the feature to mute messages
ferredoxin/QNotified pull request #511
Opened 2021-02-03 15:26 UTC by NextAlone

Signed-off-by: NextAlone <12210746+NextAlone@users.noreply.github.com>

# feat(Mute): add the feature to mute messages

## 介绍 / Description

## 更改内容 / Types of Changes

- 新功能 New Feature

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [ ] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [ ] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ ] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-02-03 15:28 UTC, singleNeuron approved these changes

2021-02-03 15:28 UTC, singleNeuron commented on app/src/main/java/cn/lliiooll/utils/MsgRecord.java
> +package cn.lliiooll.utils;
不要同时存在两个MsgRecord
https://github.com/ferredoxin/QNotified/blob/master/app/src/main/java/me/singleneuron/data/MsgRecordData.kt

2021-02-03 15:29 UTC, singleNeuron requested changes

2021-02-03 15:29 UTC, singleNeuron commented on app/src/main/java/cn/lliiooll/utils/MsgRecord.java
> +package cn.lliiooll.utils;
不要同时存在两个MsgRecord
https://github.com/ferredoxin/QNotified/blob/master/app/src/main/java/me/singleneuron/data/MsgRecordData.kt

2021-02-03 15:29 UTC, qwq233 requested changes
顺便问一句 这玩意确定能用吗

2021-02-03 15:29 UTC, qwq233 commented on app/src/main/java/cn/lliiooll/activity/MuteCfgActivity.java
> +        //invoke_virtual(bounceScrollView,"a",true,500,500,boolean.class,int.class,int.class);
delete pls

2021-02-03 15:29 UTC, qwq233 commented on app/src/main/java/cn/lliiooll/activity/MuteCfgActivity.java
> +        //invoke_virtual(bounceScrollView,"setNeedHorizontalGesture",true,boolean.class);
same

2021-02-03 15:29 UTC, qwq233 commented on app/src/main/java/cn/lliiooll/utils/MsgType.java
> +    // from com.tencent.mobileqq.data.MessageRecord
same

2021-02-03 16:15 UTC, NextAlone commented
> 顺便问一句 这玩意确定能用吗

能。测过了。啊这。

2021-02-07 04:04 UTC, lliioollcn requested changes

2021-02-07 04:04 UTC, lliioollcn commented on app/src/main/java/cn/lliiooll/activity/MuteCfgActivity.java
> +public class MuteCfgActivity extends IphoneTitleBarActivityCompat implements View.OnClickListener {
建议你改改再提交，或者等我优化优化在提交...

2021-02-07 04:06 UTC, NextAlone commented on app/src/main/java/cn/lliiooll/activity/MuteCfgActivity.java
> +public class MuteCfgActivity extends IphoneTitleBarActivityCompat implements View.OnClickListener {
那就先挂着吧，这几天也没时间

2021-02-07 08:40 UTC, closed without merging