Prepare for Jenkins CI Build
ferredoxin/QNotified pull request #514
Opened 2021-02-04 15:57 UTC by qwq233

# Prepare for Jenkins CI Build

## 介绍 / Description

## 更改内容 / Types of Changes

- build.gradle

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [ ] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [ ] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ ] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-02-04 15:57 UTC, singleNeuron commented
@qwq233 不加skip ci?

2021-02-04 15:58 UTC, qwq233 commented
@singleNeuron 加p呢 又循环了等下

2021-02-04 15:58 UTC, singleNeuron commented
@qwq233 克制的加不是不加啊

2021-02-04 16:07 UTC, singleNeuron requested changes

2021-02-04 16:07 UTC, singleNeuron commented on app/build.gradle
> +                storeFile file(project.signing.storeFilePath)
完全没必要，你又不能把这个文件传进仓库，CI还是拿不到，不如用环境变量和CI的自带流程来签名了

2021-02-04 16:10 UTC, qwq233 commented on app/build.gradle
> +                storeFile file(project.signing.storeFilePath)
jenkins可以provide config

2021-02-05 06:45 UTC, singleNeuron approved these changes

2021-02-05 06:51 UTC, cinit approved these changes

2021-02-05 06:59 UTC, merged