Add NextAlone's Utils, add entry for AutoRenewFire, simplify chat long click menu
ferredoxin/QNotified pull request #525
Opened 2021-02-07 09:57 UTC by NextAlone

# Add NextAlone's Utils, add entry for AutoRenewFire, simplify chat long click menu

## 介绍 / Description

- Fix typo …
- Add NextAlone's utils and modify LogUtils …
- Add entry for AutoRenewFire …
- Simplify chat long click menu …

## 更改内容 / Types of Changes

- 修复 Bugfix
- 新功能 New Feature

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [ ] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [ ] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ ] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-02-07 10:00 UTC, singleNeuron requested changes

2021-02-07 10:00 UTC, singleNeuron commented on app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
> -import static nil.nadph.qnotified.ui.ViewBuilder.*;
别天天import打仗了求求你们了

2021-02-08 03:48 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/activity/AlphaTestFuncActivity.java
> +            autoRenewFire.setOnLongClickListener(view -> {
你塞在里边用户用不了的

2021-02-08 03:49 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
？

2021-02-08 05:33 UTC, cinit requested changes

2021-02-08 05:33 UTC, cinit commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
?

2021-02-08 05:37 UTC, cinit submitted a review, later dismissed

2021-02-08 06:03 UTC, qwq233 requested changes

2021-02-08 06:03 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/activity/AlphaTestFuncActivity.java
> +import android.annotation.*;
按需import尽量别*

2021-02-08 06:03 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/activity/AlphaTestFuncActivity.java
> +            View autoRenewFire = newListItemButton(this, "[特供版]自动续火", "芜湖", null,
塞这里边用户用不了

2021-02-08 06:03 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
> +import nil.nadph.qnotified.ui.*;
按需import

2021-02-08 06:03 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
迷惑行为

2021-02-08 06:03 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
same

2021-02-08 06:03 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
same

2021-02-08 06:03 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
same

2021-02-09 11:53 UTC, qwq233 commented on app/src/main/java/me/kyuubiran/dialog/AutoRenewFireDialog.kt
> +    var replyMsg: String = getExFriendCfg().getStringOrDefault(AutoRenewFireMgr.MESSAGE, "🔥")
```suggestion
    var replyMsg: String = getExFriendCfg().getStringOrDefault(AutoRenewFireMgr.MESSAGE, "[续火]")
```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/activity/OmegaTestFuncActivity.java
> +
```suggestion
```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/activity/OmegaTestFuncActivity.java
> +
```suggestion
```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion
```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion
```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion
```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion
```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 11:57 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
> +
```suggestion

```

2021-02-09 12:06 UTC, qwq233 approved these changes

2021-02-09 12:11 UTC, singleNeuron approved these changes

2021-02-09 12:32 UTC, ketal178 approved these changes

2021-02-09 12:34 UTC, NextAlone commented on app/src/main/java/me/nextalone/util/LogUtils.kt
> +    logd("After--$msg")
好耶

2021-02-09 12:36 UTC, merged