feat(Purify): add hide online status and hide chat vip image
ferredoxin/QNotified pull request #544
Opened 2021-02-12 14:16 UTC by NextAlone

# feat(Purify): add hide online status and hide chat vip image 

## 介绍 / Description

- hide online status
- hide chat vip image 

## 更改内容 / Types of Changes

- 修复 Bugfix
- 新功能 New Feature

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [ ] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [ ] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ ] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-02-12 14:18 UTC, qwq233 requested changes
拆为3commit 或者我帮你

2021-02-12 14:19 UTC, qwq233 commented
顺这个feat(Purify)什么意思

2021-02-12 16:36 UTC, cinit commented on app/src/main/java/me/nextalone/hook/HideChatVipImage.kt
> +                val titleImageId = ctx.resources.getIdentifier("jp0", "id", Utils.PACKAGE_NAME_QQ)
你用的 `R.id.jp0` 跨版本兼容性如何?

2021-02-12 16:36 UTC, cinit commented on app/src/main/java/me/nextalone/hook/HideOnlineStatus.kt
> +                val subTitleLinearLayoutId = ctx.resources.getIdentifier("j65", "id", Utils.PACKAGE_NAME_QQ)
RT, 同上

2021-02-12 18:09 UTC, NextAlone commented on app/src/main/java/me/nextalone/hook/HideOnlineStatus.kt
> +                val subTitleLinearLayoutId = ctx.resources.getIdentifier("j65", "id", Utils.PACKAGE_NAME_QQ)
at least 8.4.1 up to 8.5.5

2021-02-12 18:10 UTC, NextAlone commented on app/src/main/java/me/nextalone/hook/HideChatVipImage.kt
> +                val titleImageId = ctx.resources.getIdentifier("jp0", "id", Utils.PACKAGE_NAME_QQ)
at least 8.4.1 up to 8.5.5

2021-02-13 02:04 UTC, ketal178 commented on app/src/main/java/me/nextalone/hook/HideChatVipImage.kt
> +                val titleImageId = ctx.resources.getIdentifier("jp0", "id", Utils.PACKAGE_NAME_QQ)
at least?
准确点很难吗

2021-02-13 02:08 UTC, NextAlone commented on app/src/main/java/me/nextalone/hook/HideChatVipImage.kt
> +                val titleImageId = ctx.resources.getIdentifier("jp0", "id", Utils.PACKAGE_NAME_QQ)
> at least?
> 准确点很难吗
> 

我手机里只有841~855

2021-02-13 04:49 UTC, qwq233 approved these changes

2021-02-13 14:11 UTC, NextAlone commented on app/src/main/java/me/nextalone/hook/HideChatVipImage.kt
> +                val titleImageId = ctx.resources.getIdentifier("jp0", "id", Utils.PACKAGE_NAME_QQ)
8.2.0-8.5.5，旧版本id.name不是固定的，是以id命名

2021-02-13 18:40 UTC, qwq233 submitted a review, later dismissed

2021-02-14 05:14 UTC, cinit submitted a review, later dismissed

2021-02-14 05:18 UTC, singleNeuron submitted a review, later dismissed

2021-02-14 05:27 UTC, qwq233 approved these changes

2021-02-14 07:50 UTC, singleNeuron approved these changes

2021-02-14 07:52 UTC, cinit approved these changes

2021-02-14 07:52 UTC, merged