Move functions out of main package
ferredoxin/QNotified pull request #567
Opened 2021-02-14 17:49 UTC by cinit

Signed-off-by: Null Idle <xenonhydride@gmail.com>

## 介绍 / Description
- 将功能移出主package

## 更改内容 / Types of Changes
- 增强优化 Enhancement/optimization

## 检查列表 / Checklist
- [x] Basic Test Passed

2021-02-14 17:51 UTC, singleNeuron approved these changes

2021-02-14 17:53 UTC, NextAlone submitted a review, later dismissed

2021-02-14 17:53 UTC, ketal178 approved these changes

2021-02-14 17:54 UTC, qwq233 requested changes
俩commit qwq

2021-02-15 03:38 UTC, qwq233 approved these changes

2021-02-15 03:38 UTC, NextAlone approved these changes

2021-02-15 04:49 UTC, singleNeuron approved these changes

2021-02-15 04:49 UTC, merged