Delete useless code
ferredoxin/QNotified pull request #636
Opened 2021-02-21 11:13 UTC by ketal178

# Delete useless code

## 介绍 / Description

## 更改内容 / Types of Changes
- 增强优化 Enhancement/optimization

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist
- [x] tested

2021-02-21 12:36 UTC, NextAlone approved these changes

2021-02-21 13:25 UTC, cinit approved these changes

2021-02-22 03:33 UTC, singleNeuron requested changes

2021-02-22 03:33 UTC, singleNeuron commented on app/src/main/java/me/singleneuron/qn_kernel/tlb/QQConfigTable.kt
> -//        //特征字符串："FaceManager"/"AvatarUtil"
把特征字符串这行注释删了干啥，移到对应的类里面去

2021-02-22 11:14 UTC, NextAlone commented on app/src/main/java/me/singleneuron/qn_kernel/tlb/QQConfigTable.kt
> -//        //特征字符串："FaceManager"/"AvatarUtil"
对应类里有，他也删了，、

2021-02-22 11:14 UTC, NextAlone approved these changes

2021-02-22 11:19 UTC, singleNeuron approved these changes

2021-02-22 11:22 UTC, huajijam approved these changes

2021-02-22 11:22 UTC, merged