Add HideTroopLevel
ferredoxin/QNotified pull request #718
Opened 2021-03-07 18:12 UTC by NextAlone

# Add HideTroopLevel

## 更改内容 / Types of Changes

- 新功能 New Feature

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  #713 

## 检查列表 / Checklist

- [ ] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [ ] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ ] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-03-07 22:36 UTC, ketal178 requested changes

2021-03-07 22:36 UTC, ketal178 commented on app/src/main/java/ltd/nextalone/hook/HideTroopLevel.kt
> +        "Lcom.tencent.mobileqq.activity.aio.rebuild.basechatitemlayout.TroopMemberNewLevelExtender;->a()V".method.replace(this, null)
留给我中午来写

2021-03-08 04:36 UTC, NextAlone commented on app/src/main/java/ltd/nextalone/hook/HideTroopLevel.kt
> +        "Lcom.tencent.mobileqq.activity.aio.rebuild.basechatitemlayout.TroopMemberNewLevelExtender;->a()V".method.replace(this, null)
嘤嘤嘤

2021-03-08 04:37 UTC, ketal178 commented on app/src/main/java/ltd/nextalone/hook/HideTroopLevel.kt
> +        "Lcom.tencent.mobileqq.activity.aio.rebuild.basechatitemlayout.TroopMemberNewLevelExtender;->a()V".method.replace(this, null)
马上写完

2021-03-08 05:13 UTC, ketal178 submitted a review, later dismissed

2021-03-08 08:06 UTC, cinit approved these changes

2021-03-08 08:17 UTC, ketal178 approved these changes

2021-03-08 08:17 UTC, merged