Fix AutoReceiveOriginalPhoto for qq860
ferredoxin/QNotified pull request #791
Opened 2021-04-02 16:13 UTC by ketal178

# Fix AutoReceiveOriginalPhoto for qq860

## 介绍 / Description

## 更改内容 / Types of Changes
- 修复 Bugfix

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist
- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-04-02 16:14 UTC, NextAlone requested changes

2021-04-02 16:14 UTC, NextAlone commented on app/src/main/java/ltd/nextalone/hook/AutoReceiveOriginalPhoto.kt
> +        "L${clz!!.name};->$m(Z)V".method.replace(this) {
```suggestion
        "L${clz?.name};->$m(Z)V".method.replace(this) {
```

2021-04-02 16:20 UTC, NextAlone commented on app/src/main/java/ltd/nextalone/hook/EnableQLog.kt
> +            if (m.name == "isColorLevel" && argt.isEmpty()) {
啊？没区别啊

2021-04-02 16:21 UTC, ketal178 commented on app/src/main/java/ltd/nextalone/hook/EnableQLog.kt
> +            if (m.name == "isColorLevel" && argt.isEmpty()) {
我不知道

2021-04-02 16:48 UTC, NextAlone approved these changes

2021-04-03 08:41 UTC, qwq233 approved these changes

2021-04-03 08:41 UTC, merged