Refactor HideMiniAppPullEntry
ferredoxin/QNotified pull request #857
Opened 2021-05-03 06:20 UTC by cinit

Signed-off-by: Null Idle <xenonhydride@gmail.com>

## 介绍 / Description
- 重构屏蔽下拉小程序
- 修复play屏蔽下拉小程序

## 更改内容 / Types of Changes
- 修复 Bugfix

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR
-  #777 

## 检查列表 / Checklist
- [x] Tested

2021-05-03 06:21 UTC, qwq233 requested changes
诡异的merge commit

2021-05-03 06:22 UTC, ketal178 submitted a review, later dismissed

2021-05-03 06:33 UTC, ketal178 approved these changes

2021-05-03 06:33 UTC, qwq233 approved these changes

2021-05-03 06:33 UTC, NextAlone approved these changes

2021-05-03 06:36 UTC, merged

2021-05-05 22:46 UTC, singleNeuron reviewed
请使用枚举代替诡异的 `isXXX`