Support QQ 8.8.3
ferredoxin/QNotified pull request #929
Opened 2021-06-16 00:17 UTC by NextAlone

# Support QQ 8.8.3

## 进度 / Progress

- [x] 聊天字数统计

## 更改内容 / Types of Changes

- 修复 Bugfix

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  Fixed  #928

2021-06-16 06:04 UTC, keta1 submitted a review, later dismissed

2021-06-19 10:32 UTC, qwq233 requested changes
Support QQ 8.8.3这个改成添加883的version code之类的玩意吧 commit message

2021-06-30 10:17 UTC, qwq233 requested changes
commit message

2021-07-01 03:00 UTC, qwq233 approved these changes

2021-07-01 04:43 UTC, keta1 approved these changes

2021-07-01 04:43 UTC, merged