Replace SettingsActivity with UiTable
ferredoxin/QNotified pull request #952
Opened 2021-07-14 21:02 UTC by singleNeuron

Signed-off-by: singleNeuron <Cryolitia@gmail.com>

# Replace SettingsActivity with UiTable

## 介绍 / Description

## 更改内容 / Types of Changes

- 修复 Bugfix
- 新功能 New Feature
- 增强优化 Enhancement/optimization
- UI界面 User Interface
- 内核 Core
- 文档 Documentation
- 模板 Templates

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-07-14 21:12 UTC, keta1 requested changes
中文改了

2021-07-14 21:12 UTC, keta1 commented on app/src/main/java/cc/ioctl/hook/$endGiftHook.java
> +public class $endGiftHook extends CommonDelayAbleHookBridge {
会丢配置文件
坏耶

2021-07-14 21:12 UTC, keta1 commented on app/src/main/java/me/singleneuron/qn_kernel/ui/base/UiRoutine.kt
> +val 净化功能 = arrayOf("净化功能")
奇怪的中文变量

2021-07-14 21:12 UTC, keta1 commented on app/src/main/java/cc/ioctl/hook/打开资料卡.java
> +public class 打开资料卡 {
怎么还是中文

2021-07-15 03:45 UTC, singleNeuron commented
> 中文改了

不改

2021-07-15 03:45 UTC, keta1 commented
@singleNeuron

2021-07-15 06:06 UTC, cinit approved these changes

2021-07-15 08:29 UTC, keta1 approved these changes

2021-07-15 08:29 UTC, keta1 commented on app/src/main/java/ltd/nextalone/hook/ChatWordsCount.kt
> +@me.singleneuron.qn_kernel.annotation.UiItem
怪

2021-07-15 08:29 UTC, merged