import FerredoxinUI
ferredoxin/QNotified pull request #974
Opened 2021-07-23 08:13 UTC by singleNeuron

# Import FerredoxinUI

## 更改内容 / Types of Changes
- UI界面 User Interface
- 内核 Core

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2021-07-23 09:52 UTC, qwq233 commented
run tests.

2021-07-23 10:01 UTC, qwq233 commented
run tests.

2021-07-23 10:50 UTC, qwq233 requested changes

2021-07-23 10:50 UTC, qwq233 commented on app/src/main/java/nil/nadph/qnotified/util/LicenseStatus.java
> -        long lastUpdate = ConfigManager.getDefaultConfig()
虚空了

2021-07-23 10:50 UTC, qwq233 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
最新版是7.1.1

2021-07-23 11:13 UTC, singleNeuron commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
我用的as自动升级，升到的就是702

2021-07-23 11:43 UTC, qwq233 commented on settings.gradle
> +include ':app', ':stub', ':annotations', ':compiler', ':dex-ptm', ':mmkv' , ':FerredoxinUILib', ':FerredoxinUI:demo'
```suggestion
include ':app', ':stub', ':annotations', ':compiler', ':dex-ptm', ':mmkv' , ':FerredoxinUILib'
```

2021-07-23 13:44 UTC, keta1 approved these changes

2021-07-23 19:06 UTC, qwq233 approved these changes

2021-07-23 19:06 UTC, merged

2021-07-24 02:47 UTC, loser641 commented
unsubscribe------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月24日(星期六) 凌晨3:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [ferredoxin/QNotified] import FerredoxinUI (#974)